const baseUrl = "https://script.google.com/macros/s/AKfycbyg9RmH2iFblNzWNBBL7J4SR-W003CQnDju8RPoPBINF_cD6Fdidkn7h9QLvMsL8u4z/exec";
const whatsappNumber = "917593925926";

// 💡 50g മുതൽ തുടങ്ങേണ്ട സാധനങ്ങളുടെ മലയാളം, ഇംഗ്ലീഷ് പേരുകൾ താഴെ നൽകിയിരിക്കുന്നു
const specialItems = [
  "കറിവേപ്പില", "Curry leaves", "Curryleaves",
    "മല്ലിചെപ്പ്", "Coriander", "Coriander leaves",
      "പൊതീന", "Mint", "Mint leaves"
      ]; 

      let productList = [];
      let cart = {};

      const initialUrl = `${baseUrl}?_=${new Date().getTime()}`;

      document.getElementById("products").innerHTML = "Loading products...";

      function fetchData(fetchUrl) {
        fetch(fetchUrl)
            .then(response => response.json())
                .then(data => {
                      productList = Array.isArray(data) ? data : (data.data || []);
                            displayProducts();
                                })
                                    .catch(error => {
                                          console.error("Error:", error);
                                                if(productList.length === 0) {
                                                        document.getElementById("products").innerHTML = "<p>Data Load Failed</p>";
                                                              }
                                                                  });
                                                                  }

                                                                  fetchData(initialUrl);

                                                                  // 1 മിനിറ്റിൽ പശ്ചാത്തലത്തിൽ അപ്‌ഡേറ്റ് ചെയ്യുന്നത്
                                                                  setInterval(() => {
                                                                      const refreshUrl = `${baseUrl}?_=${new Date().getTime()}`;
                                                                          fetchData(refreshUrl);
                                                                          }, 60);

                                                                          function displayProducts() {
                                                                            let html = "";

                                                                                if (productList.length === 0) {
                                                                                    document.getElementById("products").innerHTML = "<p>No products available</p>";
                                                                                        return;
                                                                                          }

                                                                                            productList.forEach((item, index) => {
                                                                                                const keys = Object.keys(item).reduce((acc, key) => {
                                                                                                      acc[key.toLowerCase().replace(/\s+/g, '')] = item[key];
                                                                                                            return acc;
                                                                                                                }, {});

                                                                                                                    let name = keys['name'] || "No Name";
                                                                                                                        let offPrice = parseFloat(keys['offerprice']) || 0;

                                                                                                                            if (name !== "No Name" && offPrice > 0) {
                                                                                                                                  const itemKey = `prod_${index}`;
                                                                                                                                        let currentQtyText = cart[itemKey] ? formatWeight(cart[itemKey].qty) : "0";

                                                                                                                                              // കറിവേപ്പില, മല്ലിചെപ്പ്, പൊതീന എന്നിവയാണോ എന്ന് പരിശോധിക്കുന്നു
                                                                                                                                                    let isSpecial = specialItems.some(special => special.toLowerCase().trim() === name.toString().toLowerCase().trim());
                                                                                                                                                          let changeValue = isSpecial ? 0.05 : 0.25;

                                                                                                                                                                html += `
                                                                                                                                                                        <div class="product">
                                                                                                                                                                                  <div class="product-details">
                                                                                                                                                                                              <p class="product-name">${name}</p>
                                                                                                                                                                                                          <p class="product-price">₹${offPrice}/kg</p>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                              <div class="qty-controls">
                                                                                                                                                                                                                                          <button class="btn-minus" onclick="changeQty('${itemKey}', '${name}', ${offPrice}, -${changeValue})">-</button>
                                                                                                                                                                                                                                                      <span class="qty-value" id="qty-${itemKey}">${currentQtyText}</span>
                                                                                                                                                                                                                                                                  <button class="btn-plus" onclick="changeQty('${itemKey}', '${name}', ${offPrice}, ${changeValue})">+</button>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                          `;
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                  document.getElementById("products").innerHTML = html;
                                                                                                                                                                                                                                                                                                    updateCartUI();
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                    //  മാറ്റേണ്ട പുതിയ കോഡ്:
                                                                                                                                                                                                                                                                                                    function changeQty(key, name, pricePerKg, change) {
                                                                                                                                                                                                                                                                                                      if (!cart[key]) {
                                                                                                                                                                                                                                                                                                          // ആദ്യമായി പ്ലസ് ബട്ടൺ അടിക്കുമ്പോൾ 0-ൽ നിന്ന് തുടങ്ങാതെ നേരെ 50g-ലേക്ക് (അല്ലെങ്കിൽ 250g-ലേക്ക്) വരാൻ:
                                                                                                                                                                                                                                                                                                              cart[key] = { name: name, price: pricePerKg, qty: change > 0 ? 0 : -change };
                                                                                                                                                                                                                                                                                                                }



                                                                                                                                                                                                                                                                                                              const latestProduct = productList.find((item, idx) => `prod_${idx}` === key);
                                                                                                                                                                                                                                                                                                                if (latestProduct) {
                                                                                                                                                                                                                                                                                                                    const keys = Object.keys(latestProduct).reduce((acc, k) => {
                                                                                                                                                                                                                                                                                                                          acc[k.toLowerCase().replace(/\s+/g, '')] = latestProduct[k];
                                                                                                                                                                                                                                                                                                                                return acc;
                                                                                                                                                                                                                                                                                                                                    }, {});
                                                                                                                                                                                                                                                                                                                                        cart[key].price = parseFloat(keys['offerprice']) || pricePerKg;
                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                            cart[key].qty += change;

                                                                                                                                                                                                                                                                                                                                              // ജാവാസ്ക്രിപ്റ്റിലെ പോയിന്റുകൾ വറ്റ വരാതിരിക്കാൻ റൗണ്ട് ചെയ്യുന്നു
                                                                                                                                                                                                                                                                                                                                                cart[key].qty = Math.round(cart[key].qty * 100) / 100;

                                                                                                                                                                                                                                                                                                                                                  if (cart[key].qty < 0) {
                                                                                                                                                                                                                                                                                                                                                      cart[key].qty = 0;
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                            if (cart[key].qty > 100) {
                                                                                                                                                                                                                                                                                                                                                                cart[key].qty = 100;
                                                                                                                                                                                                                                                                                                                                                                    alert("Maximum order capacity is 100kg");
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                        const currentQty = cart[key].qty;
                                                                                                                                                                                                                                                                                                                                                                          document.getElementById(`qty-${key}`).innerText = formatWeight(currentQty);

                                                                                                                                                                                                                                                                                                                                                                            if (currentQty === 0) {
                                                                                                                                                                                                                                                                                                                                                                                delete cart[key];
                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                    updateCartUI();
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                    function formatWeight(kg) {
                                                                                                                                                                                                                                                                                                                                                                                      if (kg === 0) return "0";

                                                                                                                                                                                                                                                                                                                                                                                          let totalGrams = Math.round(kg * 1000);
                                                                                                                                                                                                                                                                                                                                                                                            let kilograms = Math.floor(totalGrams / 1000);
                                                                                                                                                                                                                                                                                                                                                                                              let grams = totalGrams % 1000;

                                                                                                                                                                                                                                                                                                                                                                                                if (kilograms > 0 && grams > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                    return `${kilograms}kg ${grams}g`;
                                                                                                                                                                                                                                                                                                                                                                                                      } else if (kilograms > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                          return `${kilograms}kg`;
                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                return `${grams}g`;
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                  function updateCartUI() {
                                                                                                                                                                                                                                                                                                                                                                                                                    const cartItemsDiv = document.getElementById("cart-items");
                                                                                                                                                                                                                                                                                                                                                                                                                      const cartTotalDiv = document.getElementById("cart-total");

                                                                                                                                                                                                                                                                                                                                                                                                                          const activeKeys = Object.keys(cart);

                                                                                                                                                                                                                                                                                                                                                                                                                            if (activeKeys.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                cartItemsDiv.innerHTML = "Cart Empty";
                                                                                                                                                                                                                                                                                                                                                                                                                                    cartTotalDiv.innerHTML = "Total ₹0";
                                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                            let html = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                              let total = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                activeKeys.forEach(key => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const item = cart[key];

                                                                                                                                                                                                                                                                                                                                                                                                                                                            const latestProduct = productList.find((p, idx) => `prod_${idx}` === key);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (latestProduct) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const keys = Object.keys(latestProduct).reduce((acc, k) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              acc[k.toLowerCase().replace(/\s+/g, '')] = latestProduct[k];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return acc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  item.price = parseFloat(keys['offerprice']) || item.price;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const itemTotal = item.price * item.qty;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              total += itemTotal;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      html += `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="cart-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>${item.name} (${formatWeight(item.qty)})</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>₹${itemTotal.toFixed(2)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cartItemsDiv.innerHTML = html;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cartTotalDiv.innerHTML = `Total ₹${total.toFixed(2)}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function sendWhatsAppOrder() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const name = document.getElementById("cust-name").value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const phone = document.getElementById("cust-phone").value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const address = document.getElementById("cust-address").value.trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const activeKeys = Object.keys(cart);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (activeKeys.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("Please add items to your cart first!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!name || !phone || !address) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert("Please fill Name, Phone, and Address.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let message = `*New Vegetable Order From NSI VEGETABLES*\n\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message += `*Customer Details:*\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message += `Name: ${name}\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      message += `Phone: ${phone}\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message += `Address: ${address}\n\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          message += `*Items:*\n`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let grandTotal = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              activeKeys.forEach((key, index) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const item = cart[key];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const itemTotal = item.price * item.qty;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          grandTotal += itemTotal;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              message += `${index + 1}. ${item.name} - ${formatWeight(item.qty)} (₹${itemTotal.toFixed(2)})\n`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message += `\n*Total: ₹${grandTotal.toFixed(2)}*`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const encodedMessage = encodeURIComponent(message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const whatsappUrl = `https://api.whatsapp.com/send?phone=${whatsappNumber}&text=${encodedMessage}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          window.open(whatsappUrl, '_blank');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      